import { useRef, useMemo } from 'react';
import { useFrame } from '@react-three/fiber';
import { Html } from '@react-three/drei';
import * as THREE from 'three';

interface CrownOverlayProps {
  visible: boolean;
}

// Crown sits on a right premolar tooth.
// Real model data (centered, raw units): tooth cluster at ~345deg angle
// avgPos raw ~(29, 3, -6), topY raw ~20.  At scale 0.055: (1.595, 0.165, -0.33), topY 1.1
const CROWN_CENTER_RAW: [number, number, number] = [29, 2, -5];
const S = 0.055;

export default function CrownOverlay({ visible }: CrownOverlayProps) {
  const matRef = useRef<THREE.MeshPhysicalMaterial>(null);
  const startTimeRef = useRef<number | null>(null);

  const { crownGeo, crownPos, labelPos } = useMemo(() => {
    const cx = CROWN_CENTER_RAW[0] * S;
    const cy = CROWN_CENTER_RAW[1] * S;
    const cz = CROWN_CENTER_RAW[2] * S;

    // Tooth dimensions in world coords (roughly 8mm wide, 10mm tall at this scale)
    const toothWidth = 0.04;   // half-width of the crown
    const toothHeight = 0.065; // height of the crown

    // Tooth profile for LatheGeometry (cross section rotated around Y)
    const points: THREE.Vector2[] = [];
    const segs = 16;
    for (let i = 0; i <= segs; i++) {
      const t = i / segs; // 0=margin, 1=occlusal
      let r: number;
      if (t < 0.05) r = toothWidth * 0.75;              // thin margin edge
      else if (t < 0.25) r = toothWidth * (0.75 + 0.3 * ((t - 0.05) / 0.2));  // cervical widening
      else if (t < 0.65) r = toothWidth * (1.05 - 0.04 * Math.cos(((t - 0.25) / 0.4) * Math.PI)); // body barrel
      else if (t < 0.9) r = toothWidth * (1.01 - 0.12 * ((t - 0.65) / 0.25)); // taper to cusps
      else r = toothWidth * 0.85;                         // occlusal platform
      points.push(new THREE.Vector2(r, t * toothHeight));
    }

    const geo = new THREE.LatheGeometry(points, 20);

    return {
      crownGeo: geo,
      crownPos: [cx, cy, cz] as [number, number, number],
      labelPos: [0, toothHeight + 0.03, 0] as [number, number, number],
    };
  }, []);

  useFrame(() => {
    if (!visible || !matRef.current) {
      startTimeRef.current = null;
      if (matRef.current) matRef.current.opacity = 0;
      return;
    }

    if (startTimeRef.current === null) startTimeRef.current = performance.now();
    const elapsed = performance.now() - startTimeRef.current;
    const progress = Math.min(elapsed / 1500, 1);
    const eased = 1 - Math.pow(1 - progress, 2);
    matRef.current.opacity = eased * 0.4;
  });

  if (!visible) return null;

  return (
    <group position={crownPos}>
      <mesh geometry={crownGeo}>
        <meshPhysicalMaterial
          ref={matRef}
          color="#88D4F0"
          transparent
          opacity={0}
          roughness={0.15}
          metalness={0.05}
          clearcoat={0.6}
          clearcoatRoughness={0.1}
          side={THREE.DoubleSide}
          depthWrite={false}
        />
      </mesh>
      <Html position={labelPos} center distanceFactor={8} style={{ pointerEvents: 'none' }}>
        <div
          className="px-2 py-0.5 rounded-full text-[10px] font-medium whitespace-nowrap"
          style={{
            background: 'linear-gradient(135deg, rgba(0,154,206,0.15), rgba(139,92,246,0.15))',
            color: '#8B5CF6',
            border: '1px solid rgba(139,92,246,0.2)',
            backdropFilter: 'blur(4px)',
          }}
        >
          Generated by AI
        </div>
      </Html>
    </group>
  );
}
